language: java

jdk:
    -openjdk11

addons:
    sonarcloud:
        organization: "gabrielequatrana"
        token: "b66b5be3b685c0770a2bd3a69bab00ee06e8376e"
        
script:
    -ant build
    -sonar-scanner